---
- name: Install Packages
  xbps:
    pkg: node_exporter
    state: present

- name: Configure Firewall
  copy:
    src: node_exporter.rules
    dest: /etc/iptables.d/node_exporter.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Enable Service
  service:
    name: node_exporter
    enabled: yes

- name: Install Consul Service
  template:
    src: node_exporter.hcl
    dest: "{{node_exporter_consul_path}}"
    owner: root
    group: root
    mode: 0644
  when:
    - node_exporter_consul_path is defined
    - node_exporter_consul_token is defined
